### PR TITLE
Completed implementation

### PR DESCRIPTION
**Pull request by madpilot**
Hi,

This mega PR finishes the rest of the implementation, and adds documentation.

Note that the interface has changed slightly - Item#get_item has now become Item#fetch (to make it more generic for the rest of the classes), and Items#to_a has been removed, replaced for Items#fetch

There is also now a config object so you can supply username and api_keys without using environmental variables (ENV still works though).

Let me know what you think!

Thanks.

### CODE REVIEW

**Comment by barnabyalter** [comment]
@madpilot Hey looks great! Thanks for finishing/rewriting the whole thing. I'm happy to merge. Considering you completed the implementation I can release this as v1.0.0 and will throw up on rubygems too.

**Comment by madpilot** [comment]
Awesome! There will probably be a couple of PRs over the next couple of days, as I pick up any real-world issues as I finish our implementation.

**Comment by barnabyalter** [comment]
@madpilot https://rubygems.org/gems/gather_content-api

I can add you to the authors list if you want

**Comment by madpilot** [comment]
That would be ace! Cheers!

----------------------------------------------
Myles Eftos
Mobile: +61-409-293-183

**Pull request merged**
